name: Deploy to GitHub Pages
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Build and Deploy
          uses: JamesIves/github-pages-deploy-action@master
          env:
            ACCESS_TOKEN: 62ba9aa98c5a39d635d2c1c35aef763c9fd83609
            BRANCH: master
            FOLDER: src
            BUILD_SCRIPT: npm install && npm run-script build-and-deploy
